from pathlib import Path

from oduflow import resource_plan
from oduflow.resource_plan import (
    build_resource_plan,
    plan_fingerprint,
    tune_marker,
    tune_status,
)


class TestResourcePlan:
    def test_dev_only_preserves_lean_profile(self):
        plan = build_resource_plan(4096, 4, production_enabled=False)

        assert plan.dev_postgres.shared_buffers_mb == 410
        assert plan.dev_postgres.effective_cache_size_mb == 1230
        assert plan.dev_postgres.cpu_count == 4
        assert plan.production_postgres is None
        assert plan.production_odoo_ram_budget_mb == 0

    def test_production_mode_coordinates_host_budgets(self):
        plan = build_resource_plan(16384, 8, production_enabled=True)

        assert plan.dev_postgres.shared_buffers_mb == 512
        assert plan.production_postgres is not None
        assert plan.production_postgres.shared_buffers_mb == 3277
        assert (
            plan.dev_postgres.shared_buffers_mb
            + plan.production_postgres.shared_buffers_mb
            <= round(plan.host_ram_mb * 0.25)
        )
        assert plan.dev_postgres.cpu_count == 4
        assert plan.production_postgres.cpu_count == 4
        assert plan.production_odoo_cpu_count == 6
        assert plan.production_odoo_ram_budget_mb == 7373

    def test_production_mode_reduces_dev_claim(self):
        dev_only = build_resource_plan(8192, 4, production_enabled=False)
        combined = build_resource_plan(8192, 4, production_enabled=True)

        assert dev_only.dev_postgres.shared_buffers_mb == 819
        assert combined.dev_postgres.shared_buffers_mb == 410
        assert combined.dev_postgres.effective_cache_size_mb == 819

    def test_tiny_production_host_keeps_safe_floors(self):
        plan = build_resource_plan(1024, 1, production_enabled=True)

        assert plan.dev_postgres.shared_buffers_mb == 128
        assert plan.production_postgres is not None
        assert plan.production_postgres.shared_buffers_mb == 512
        assert plan.dev_postgres.cpu_count == 1
        assert plan.production_postgres.cpu_count == 1


class TestTuneFingerprint:
    def test_fingerprint_changes_with_mode_and_resources(self):
        dev = build_resource_plan(8192, 4, production_enabled=False)
        prod = build_resource_plan(8192, 4, production_enabled=True)
        larger = build_resource_plan(16384, 4, production_enabled=True)

        assert plan_fingerprint(dev, "dev") != plan_fingerprint(prod, "dev")
        assert plan_fingerprint(prod, "dev") != plan_fingerprint(larger, "dev")
        assert plan_fingerprint(prod, "dev") != plan_fingerprint(prod, "production")

    def test_status_distinguishes_managed_and_custom_configs(self):
        plan = build_resource_plan(8192, 4, production_enabled=True)
        marker = tune_marker(plan, "dev")

        assert tune_status(None, marker) == "missing"
        assert tune_status(f"# KEEP\n{marker}\n", marker) == "current"
        assert (
            tune_status(
                "# KEEP\n# ODUFLOW-TUNE planner=1 profile=dev "
                "fingerprint=old production=on\n",
                marker,
            )
            == "stale"
        )
        assert (
            tune_status(
                "# KEEP\n# PostgreSQL configuration auto-generated by Oduflow\n",
                marker,
            )
            == "legacy"
        )
        assert (
            tune_status(
                "# PostgreSQL Configuration\n# Server: 2 vCPU, 4 GB RAM, HDD\n",
                marker,
            )
            == "legacy"
        )
        assert tune_status("# KEEP\n# operator config\n", marker) == "custom"

    def test_bundled_static_config_is_legacy(self):
        plan = build_resource_plan(4096, 2, production_enabled=False)
        bundled = Path(resource_plan.__file__).with_name("templates") / (
            "postgresql.conf"
        )

        assert tune_status(bundled.read_text(), tune_marker(plan, "dev")) == "legacy"
