"""Container image build jobs: validation, persistence, in-memory registry.

A build job is created by the ``start_image_build`` MCP tool, runs in a
background thread (see ``docker_ops/build_ops.py``) and is polled with
``get_image_build``. The in-memory store is the authority for jobs owned by
this process; ``job.json`` under the team data dir preserves history and keeps
*successful* builds publishable across restarts (their staging image lives in
the local Docker daemon). There is deliberately no resume: a job found on disk
in a non-terminal state without a live in-process owner is marked
``interrupted`` on first access and its sealed context is removed — retry is a
new ``start_image_build`` call (cheap, thanks to the daemon's layer cache).
"""

from __future__ import annotations

import json
import os
import posixpath
import re
import secrets
import shutil
import threading
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any

from oduflow.errors import BusyError, NotFoundError
from oduflow.settings import TeamSettings

# OCI repository name relative to the team's configured prefix ("app",
# "tools/builder"). Lowercase only, no silent normalization.
_REPOSITORY_RE = re.compile(
    r"^[a-z0-9]+(?:[._-][a-z0-9]+)*(?:/[a-z0-9]+(?:[._-][a-z0-9]+)*)*$"
)
# OCI/Docker tag grammar, 128 chars max. `latest`, semver, branch-like tags —
# any syntactically valid tag is accepted; tag naming is not an authz boundary.
_TAG_RE = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$")
# Build IDs are generated by new_build_id() and validated before any path join,
# so a caller-supplied ID can never traverse out of the team's jobs directory.
_BUILD_ID_RE = re.compile(r"^bld-[a-f0-9]{12}$")

_MAX_TAGS_PER_PUBLISH = 10
_MAX_TAIL_BYTES = 2 * 1024 * 1024

STATUS_QUEUED = "queued"
STATUS_BUILDING = "building"
STATUS_SUCCEEDED = "succeeded"
STATUS_FAILED = "failed"
STATUS_CANCELLED = "cancelled"
STATUS_INTERRUPTED = "interrupted"
TERMINAL_STATUSES = frozenset(
    {STATUS_SUCCEEDED, STATUS_FAILED, STATUS_CANCELLED, STATUS_INTERRUPTED}
)


def new_build_id() -> str:
    return f"bld-{secrets.token_hex(6)}"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def validate_repository(repository: str) -> str:
    """Validate a destination repository relative to the team's prefix."""
    repository = (repository or "").strip().strip("/")
    if not repository:
        raise ValueError(
            "repository is required — the destination path below the team's "
            "configured repository_prefix (e.g. 'app')."
        )
    if len(repository) > 200 or not _REPOSITORY_RE.match(repository):
        raise ValueError(
            f"Invalid repository {repository!r}: must be a lowercase OCI "
            "repository path (letters/digits with . _ - separators, '/' "
            "between components), relative to the configured prefix."
        )
    return repository


def validate_tags(raw: str) -> list[str]:
    """Parse a comma-separated tag list; order kept, duplicates dropped."""
    tags: list[str] = []
    for part in (raw or "").split(","):
        tag = part.strip()
        if not tag:
            continue
        if not _TAG_RE.match(tag):
            raise ValueError(
                f"Invalid tag {tag!r}: tags must match "
                "[A-Za-z0-9_][A-Za-z0-9._-]* and be at most 128 characters."
            )
        if tag not in tags:
            tags.append(tag)
    if not tags:
        raise ValueError("tags is required — comma-separated, e.g. '1.4.0,latest'.")
    if len(tags) > _MAX_TAGS_PER_PUBLISH:
        raise ValueError(f"At most {_MAX_TAGS_PER_PUBLISH} tags per publish call.")
    return tags


def validate_relative_path(path: str, what: str) -> str:
    """Normalize a caller-supplied path that must stay below the checkout."""
    path = (path or "").strip()
    if not path or path == ".":
        return "."
    if "\x00" in path:
        raise ValueError(f"Invalid {what}: NUL byte in path.")
    if path.startswith(("/", "\\")):
        raise ValueError(f"Invalid {what} {path!r}: must be a relative path.")
    normalized = posixpath.normpath(path.replace("\\", "/"))
    if normalized == ".." or normalized.startswith("../"):
        raise ValueError(f"Invalid {what} {path!r}: escapes the checkout.")
    return normalized


def validate_build_id(build_id: str) -> str:
    build_id = (build_id or "").strip()
    if not _BUILD_ID_RE.match(build_id):
        raise ValueError(f"Invalid build_id {build_id!r}.")
    return build_id


@dataclass
class BuildJob:
    """One image build: source pin, status, and its publication history."""

    build_id: str
    team_id: str
    env_name: str
    branch: str
    dockerfile: str
    context: str
    target: str = ""
    build_arg_names: list[str] = field(default_factory=list)
    commit: str = ""
    status: str = STATUS_QUEUED
    created_at: str = ""
    finished_at: str = ""
    error: str = ""
    image_id: str = ""
    local_tag: str = ""
    publications: list[dict[str, Any]] = field(default_factory=list)
    # SHA-256 of the environment's persistent MCP token. The secret itself is
    # never stored; its digest is stable across rename and changes on recreate.
    owner_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @staticmethod
    def from_dict(data: dict[str, Any]) -> BuildJob:
        known = {f for f in BuildJob.__dataclass_fields__}
        return BuildJob(**{k: v for k, v in data.items() if k in known})


class BuildJobStore:
    """In-memory registry of active jobs + on-disk job.json history per team."""

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._active: dict[str, BuildJob] = {}
        self._cancel_events: dict[str, threading.Event] = {}

    # -- paths --

    @staticmethod
    def jobs_dir(team: TeamSettings) -> str:
        return os.path.join(team.data_dir, "image_builds")

    def job_dir(self, team: TeamSettings, build_id: str) -> str:
        return os.path.join(self.jobs_dir(team), validate_build_id(build_id))

    def job_json_path(self, team: TeamSettings, build_id: str) -> str:
        return os.path.join(self.job_dir(team, build_id), "job.json")

    def log_path(self, team: TeamSettings, build_id: str) -> str:
        return os.path.join(self.job_dir(team, build_id), "build.log")

    def context_dir(self, team: TeamSettings, build_id: str) -> str:
        return os.path.join(self.job_dir(team, build_id), "context")

    # -- lifecycle --

    def create(
        self,
        team: TeamSettings,
        env_name: str,
        branch: str,
        dockerfile: str,
        context: str,
        target: str = "",
        build_arg_names: list[str] | None = None,
        owner_id: str = "",
        max_concurrent_builds: int = 2,
    ) -> BuildJob:
        with self._lock:
            active_count = sum(
                job.team_id == team.team_id for job in self._active.values()
            )
            if active_count >= max_concurrent_builds:
                raise BusyError(
                    f"Team '{team.team_id}' already has {active_count} active image "
                    f"build(s); the configured maximum is {max_concurrent_builds}. "
                    "Wait for one to finish or cancel it."
                )
            build_id = new_build_id()
            while build_id in self._active or os.path.exists(
                self.job_dir(team, build_id)
            ):
                build_id = new_build_id()
            job = BuildJob(
                build_id=build_id,
                team_id=team.team_id,
                env_name=env_name,
                branch=branch,
                dockerfile=dockerfile,
                context=context,
                target=target,
                build_arg_names=sorted(build_arg_names or []),
                created_at=now_iso(),
                owner_id=owner_id,
            )
            self._active[job.build_id] = job
            self._cancel_events[job.build_id] = threading.Event()
        try:
            os.makedirs(self.job_dir(team, job.build_id), exist_ok=False)
            self.save(team, job)
        except Exception:
            with self._lock:
                self._active.pop(job.build_id, None)
                self._cancel_events.pop(job.build_id, None)
            raise
        return job

    def save(self, team: TeamSettings, job: BuildJob) -> None:
        path = self.job_json_path(team, job.build_id)
        tmp = path + ".tmp"
        with open(tmp, "w") as f:
            json.dump(job.to_dict(), f, indent=2)
        os.replace(tmp, path)

    def finish(
        self, team: TeamSettings, job: BuildJob, status: str, error: str = ""
    ) -> None:
        """Move a job to a terminal state and drop its sealed context."""
        with self._lock:
            job.status = status
            job.error = error
            job.finished_at = now_iso()
            self._active.pop(job.build_id, None)
            self._cancel_events.pop(job.build_id, None)
        self.save(team, job)
        shutil.rmtree(self.context_dir(team, job.build_id), ignore_errors=True)

    def load(
        self, team: TeamSettings, env_name: str, owner_id: str, build_id: str
    ) -> BuildJob:
        """Load a job, enforcing team + environment ownership.

        Possession of a build ID is not authorization: the lookup is rooted in
        the caller's team data dir and the recorded environment identity must
        match. The identity survives rename but changes on delete/recreate. A
        mismatch reports plain not-found so other environments' builds are not
        disclosed. On-disk jobs left non-terminal by a dead process are marked
        interrupted here (lazy cleanup — there is no startup reconciliation).
        """
        build_id = validate_build_id(build_id)
        with self._lock:
            active = self._active.get(build_id)
            if active is not None:
                if active.team_id != team.team_id or active.owner_id != owner_id:
                    raise NotFoundError(self._missing(build_id, env_name))
                return active
        path = self.job_json_path(team, build_id)
        try:
            with open(path) as f:
                job = BuildJob.from_dict(json.load(f))
        except (OSError, ValueError, TypeError):
            raise NotFoundError(self._missing(build_id, env_name))
        if job.team_id != team.team_id or not owner_id or job.owner_id != owner_id:
            raise NotFoundError(self._missing(build_id, env_name))
        if job.status not in TERMINAL_STATUSES:
            # Recorded as running, but no live owner in this process: the
            # server restarted mid-build. The buildctl-less design has nothing
            # to resume — make the interruption explicit and retryable.
            job.status = STATUS_INTERRUPTED
            job.error = (
                "The Oduflow server restarted while this build was in "
                "progress. Start a new build to retry."
            )
            job.finished_at = job.finished_at or now_iso()
            self.save(team, job)
            shutil.rmtree(self.context_dir(team, build_id), ignore_errors=True)
        return job

    @staticmethod
    def _missing(build_id: str, env_name: str) -> str:
        return f"Build '{build_id}' not found for environment '{env_name}'."

    def cancel_event(self, build_id: str) -> threading.Event | None:
        with self._lock:
            return self._cancel_events.get(build_id)

    def append_publication(
        self, team: TeamSettings, job: BuildJob, publication: dict[str, Any]
    ) -> None:
        with self._lock:
            job.publications.append(publication)
        self.save(team, job)

    def read_log_tail(self, team: TeamSettings, build_id: str, tail_lines: int) -> str:
        path = self.log_path(team, build_id)
        tail_lines = max(1, min(int(tail_lines), 2000))
        try:
            with open(path, "rb") as f:
                f.seek(0, os.SEEK_END)
                size = f.tell()
                start = max(0, size - _MAX_TAIL_BYTES)
                f.seek(start)
                raw = f.read()
        except OSError:
            return ""
        text = raw.decode(errors="replace")
        if start:
            # The bounded read may begin in the middle of a line.
            _partial, separator, text = text.partition("\n")
            if not separator:
                return ""
        lines = text.splitlines(keepends=True)
        return "".join(lines[-tail_lines:])

    def list_jobs(self, team: TeamSettings) -> list[BuildJob]:
        """Load persisted jobs for team-local retention and cleanup."""
        jobs: list[BuildJob] = []
        try:
            entries = os.scandir(self.jobs_dir(team))
        except OSError:
            return jobs
        with entries:
            for entry in entries:
                if not entry.is_dir() or not _BUILD_ID_RE.match(entry.name):
                    continue
                try:
                    with open(self.job_json_path(team, entry.name)) as f:
                        job = BuildJob.from_dict(json.load(f))
                except (OSError, ValueError, TypeError):
                    continue
                if job.team_id == team.team_id:
                    jobs.append(job)
        return jobs


store = BuildJobStore()
