"""Generate a resource-tuned postgresql.conf at first system initialization.

Oduflow runs ONE shared PostgreSQL instance serving many ephemeral per-branch
Odoo databases. Each Odoo environment is single-user and lightweight
(``workers=0``, ``db_maxconn=8``, ``max_cron_threads=0`` — see
``templates/odoo.conf``): one developer or one agent testing the UI. The host
runs MANY such containers, so RAM should stay available for them rather than be
locked into one big database. The tuning here is therefore deliberately *lean*
(small ``shared_buffers``), scales gently with the detected resources, and
assumes SSD storage.

The generated file starts with a ``# KEEP`` marker so ``oduflow upgrade`` never
overwrites it (see ``_run_upgrade`` in ``server.py``).
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger("oduflow")

# Fixed connection ceiling for the shared instance. With db_maxconn=8 per Odoo
# environment this comfortably covers ~10-12 concurrently active environments.
DEFAULT_MAX_CONNECTIONS = 100

# Fallbacks when neither the Docker daemon nor host introspection report usable
# numbers (matches the assumptions baked into the legacy bundled config).
_DEFAULT_CPU = 2
_DEFAULT_RAM_MB = 4096.0


def detect_resources() -> dict[str, Any]:
    """Detect CPU count and total RAM available to the PostgreSQL container.

    Prefers the Docker daemon's view (``docker info`` → ``NCPU``/``MemTotal``),
    which is correct both for native Linux and the Docker Desktop VM on macOS.
    Falls back to host introspection, then to conservative defaults. Never
    raises — resource detection must not block initialization.
    """
    try:
        from oduflow.docker_ops.client import get_client

        info = get_client().info()
        ncpu = int(info.get("NCPU") or 0)
        mem_bytes = int(info.get("MemTotal") or 0)
        if ncpu > 0 and mem_bytes > 0:
            return {
                "cpu_count": ncpu,
                "total_ram_mb": mem_bytes / (1024 * 1024),
                "source": "docker",
            }
    except Exception:
        logger.debug("docker info unavailable for postgres tuning", exc_info=True)

    try:
        from oduflow.docker_ops.stats import get_system_stats

        stats = get_system_stats()
        cpu = int(stats.get("cpu_count") or 0)
        ram = float(stats.get("mem_total_mb") or 0.0)
        if cpu > 0 and ram > 0:
            return {"cpu_count": cpu, "total_ram_mb": ram, "source": "host"}
    except Exception:
        logger.debug("host stats unavailable for postgres tuning", exc_info=True)

    return {
        "cpu_count": _DEFAULT_CPU,
        "total_ram_mb": _DEFAULT_RAM_MB,
        "source": "defaults",
    }


def _clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def generate_postgresql_conf(
    total_ram_mb: float,
    cpu_count: int,
    *,
    max_connections: int = DEFAULT_MAX_CONNECTIONS,
    source: str = "auto",
    oduflow_version: str = "",
) -> str:
    """Render a lean, SSD-oriented postgresql.conf for the given resources.

    Pure function (no I/O) so it is fully unit-testable. ``source`` and
    ``oduflow_version`` only feed the informational header.
    """
    ram = max(int(total_ram_mb), 0)
    cpu = max(int(cpu_count), 1)
    mc = max(int(max_connections), 1)

    # Memory: keep PostgreSQL small so RAM stays free for the many Odoo
    # containers. ~10% of RAM for shared_buffers, floored at 128MB, capped at
    # 1GB regardless of host size.
    shared_buffers = int(_clamp(round(ram * 0.10), 128, 1024))
    effective_cache = shared_buffers * 3
    work_mem = int(_clamp(shared_buffers // mc, 4, 16))
    maintenance_work_mem = int(_clamp(shared_buffers // 2, 64, 256))
    wal_buffers = int(_clamp(round(shared_buffers * 0.03), 4, 16))

    # Parallelism: low-concurrency single-user workloads barely benefit and
    # extra workers cost memory, so cap it tightly.
    par_gather = min(cpu // 2, 2)
    par_maint = max(min(cpu // 2, 2), 1)
    autovac_workers = min(cpu, 3)

    version_note = f" {oduflow_version}".rstrip()

    return f"""# KEEP
# PostgreSQL configuration auto-generated by Oduflow{version_note} on first launch.
# Detected: {cpu} vCPU, {ram} MB RAM (source: {source}).
# Tuned lean for many lightweight single-user Odoo environments (workers=0,
# db_maxconn=8) sharing one PostgreSQL instance on SSD storage.
#
# Edit freely: the leading "# KEEP" line stops `oduflow upgrade` from
# overwriting this file. To regenerate from current resources: delete this
# file, restart the oduflow server, then restart the oduflow-db container.

# =============================================================================
# CONNECTION SETTINGS
# =============================================================================
listen_addresses = '*'
port = 5432
max_connections = {mc}

# =============================================================================
# MEMORY (lean: keep RAM available for Odoo containers)
# =============================================================================
shared_buffers = {shared_buffers}MB
work_mem = {work_mem}MB
maintenance_work_mem = {maintenance_work_mem}MB
effective_cache_size = {effective_cache}MB

# =============================================================================
# WAL (Write-Ahead Log)
# =============================================================================
wal_level = replica
wal_buffers = {wal_buffers}MB
min_wal_size = 256MB
max_wal_size = 1GB
checkpoint_completion_target = 0.9
checkpoint_timeout = 15min

# =============================================================================
# QUERY PLANNER (SSD)
# =============================================================================
random_page_cost = 1.1
seq_page_cost = 1.0
effective_io_concurrency = 200

# =============================================================================
# PARALLEL QUERIES
# =============================================================================
max_worker_processes = {cpu}
max_parallel_workers_per_gather = {par_gather}
max_parallel_workers = {cpu}
max_parallel_maintenance_workers = {par_maint}

# =============================================================================
# LOGGING
# =============================================================================
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_rotation_age = 1d
log_rotation_size = 100MB
log_min_duration_statement = 1000
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

# =============================================================================
# AUTOVACUUM
# =============================================================================
autovacuum = on
autovacuum_max_workers = {autovac_workers}
autovacuum_naptime = 30s
autovacuum_vacuum_threshold = 50
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_threshold = 50
autovacuum_analyze_scale_factor = 0.025
autovacuum_vacuum_cost_delay = 20ms

# =============================================================================
# LOCALE & ENCODING
# =============================================================================
lc_messages = 'en_US.UTF-8'
lc_monetary = 'en_US.UTF-8'
lc_numeric = 'en_US.UTF-8'
lc_time = 'en_US.UTF-8'
default_text_search_config = 'pg_catalog.english'

# =============================================================================
# MISC
# =============================================================================
synchronous_commit = on
full_page_writes = on
huge_pages = off
"""
