"""Resource tuning for the production tier (PostgreSQL conf + Odoo workers).

The production PostgreSQL instance is the opposite of the dev one tuned in
:mod:`oduflow.pg_tune`: few long-lived multi-user databases instead of many
ephemeral single-user ones. The two profiles are co-designed for one host —
the dev instance caps ``shared_buffers`` at 1 GB regardless of host size,
which is why production can take a real share (20% RAM shared_buffers, 45%
effective_cache_size) without a coordinator between them.

WAL archiving is enabled from day one (``archive_mode`` requires a restart
to toggle, so it ships on) with a no-op ``archive_command``; the backup
subsystem flips the command to WAL-G via ``ALTER SYSTEM`` + reload when a
[backup] section is configured (see :mod:`oduflow.walg`).

Like pg_tune, the generated file starts with ``# KEEP`` so ``oduflow
upgrade`` never overwrites it, and generators here are pure functions.
"""

from __future__ import annotations

import logging

from oduflow.pg_tune import _clamp

logger = logging.getLogger("oduflow")

# The production cluster hosts a handful of databases with workers>0 Odoo
# instances. db_maxconn per production is 2*workers+3 (~20), so 200 covers
# many productions plus maintenance connections with room to spare.
PROD_MAX_CONNECTIONS = 200


def generate_prod_postgresql_conf(
    total_ram_mb: float,
    cpu_count: int,
    *,
    max_connections: int = PROD_MAX_CONNECTIONS,
    source: str = "auto",
    oduflow_version: str = "",
) -> str:
    """Render the production postgresql.conf for the given resources.

    Pure function (no I/O) so it is fully unit-testable.
    """
    ram = max(int(total_ram_mb), 0)
    cpu = max(int(cpu_count), 1)
    mc = max(int(max_connections), 1)

    # Memory: production gets a real share. 20% of RAM for shared_buffers
    # (floored at 512MB, capped at 8GB), 45% advertised as OS cache.
    shared_buffers = int(_clamp(round(ram * 0.20), 512, 8192))
    effective_cache = int(_clamp(round(ram * 0.45), 1024, 65536))
    work_mem = int(_clamp(shared_buffers // (mc // 4 or 1), 8, 64))
    maintenance_work_mem = int(_clamp(shared_buffers // 4, 128, 1024))
    wal_buffers = int(_clamp(round(shared_buffers * 0.03), 8, 64))

    par_gather = max(cpu // 2, 2) if cpu >= 4 else min(cpu, 2)
    par_maint = max(min(cpu // 2, 4), 1)
    autovac_workers = int(_clamp(cpu // 2, 3, 6))

    version_note = f" {oduflow_version}".rstrip()

    return f"""# KEEP
# Production PostgreSQL configuration auto-generated by Oduflow{version_note}.
# Detected: {cpu} vCPU, {ram} MB RAM (source: {source}).
# Tuned for a few long-lived multi-user production Odoo databases sharing
# this dedicated instance on SSD storage. The dev instance (oduflow-db) is
# tuned lean (shared_buffers <= 1GB), so both fit one host.
#
# Edit freely: the leading "# KEEP" line stops `oduflow upgrade` from
# overwriting this file. To regenerate from current resources: delete this
# file, restart the oduflow server, then restart the oduflow-prod-db
# container. Note: archive_command is managed via ALTER SYSTEM by the
# backup subsystem and lives in postgresql.auto.conf, not here.

# =============================================================================
# CONNECTION SETTINGS
# =============================================================================
listen_addresses = '*'
port = 5432
max_connections = {mc}

# =============================================================================
# MEMORY
# =============================================================================
shared_buffers = {shared_buffers}MB
work_mem = {work_mem}MB
maintenance_work_mem = {maintenance_work_mem}MB
effective_cache_size = {effective_cache}MB

# =============================================================================
# WAL / ARCHIVING (continuous archiving hooks for WAL-G)
# =============================================================================
wal_level = replica
wal_buffers = {wal_buffers}MB
min_wal_size = 512MB
max_wal_size = 4GB
checkpoint_completion_target = 0.9
checkpoint_timeout = 15min
# archive_mode cannot be toggled without a restart, so it ships enabled.
# The actual command is set via ALTER SYSTEM (postgresql.auto.conf) by the
# backup subsystem: /bin/true when backups are unconfigured, wal-g wal-push
# when a [backup] section is present.
archive_mode = on
archive_command = '/bin/true'
archive_timeout = 60

# =============================================================================
# QUERY PLANNER (SSD)
# =============================================================================
random_page_cost = 1.1
seq_page_cost = 1.0
effective_io_concurrency = 200

# =============================================================================
# PARALLEL QUERIES
# =============================================================================
max_worker_processes = {cpu}
max_parallel_workers_per_gather = {par_gather}
max_parallel_workers = {cpu}
max_parallel_maintenance_workers = {par_maint}

# =============================================================================
# LOGGING
# =============================================================================
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d.log'
log_rotation_age = 1d
log_rotation_size = 100MB
log_min_duration_statement = 1000
log_checkpoints = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 1000
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

# =============================================================================
# AUTOVACUUM
# =============================================================================
autovacuum = on
autovacuum_max_workers = {autovac_workers}
autovacuum_naptime = 30s
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.025

# =============================================================================
# LOCALE & ENCODING
# =============================================================================
lc_messages = 'en_US.UTF-8'
lc_monetary = 'en_US.UTF-8'
lc_numeric = 'en_US.UTF-8'
lc_time = 'en_US.UTF-8'
default_text_search_config = 'pg_catalog.english'

# =============================================================================
# MISC
# =============================================================================
synchronous_commit = on
full_page_writes = on
huge_pages = off
"""


def compute_odoo_worker_settings(
    cpu_count: int,
    total_ram_mb: float,
    *,
    workers_cap: int = 8,
) -> dict[str, str]:
    """Auto-tuned [options] overrides for a production odoo.conf.

    Follows the standard Odoo sizing formula (workers ≈ 2*CPU + 1) bounded
    by a RAM budget of ~1 GB per worker over 45% of host RAM (the rest is
    PostgreSQL + OS cache + other containers) and by ``workers_cap``.
    Returned values are strings ready for ConfigParser interpolation.
    """
    cpu = max(int(cpu_count), 1)
    ram = max(int(total_ram_mb), 0)
    ram_budget_workers = max(int(ram * 0.45) // 1024, 2)
    workers = int(_clamp(2 * cpu + 1, 2, min(int(workers_cap), ram_budget_workers)))
    return {
        "workers": str(workers),
        "max_cron_threads": "1",
        # Odoo defaults, made explicit (bytes).
        "limit_memory_soft": str(2048 * 1024 * 1024),
        "limit_memory_hard": str(2560 * 1024 * 1024),
        "limit_time_cpu": "600",
        "limit_time_real": "1200",
        "limit_request": "65536",
        "db_maxconn": str(max(2 * workers + 3, 16)),
        # Production runs behind Traefik.
        "proxy_mode": "True",
        "list_db": "False",
    }
