"""Per-team registry of production environments (productions.json).

Productions are precious, long-lived resources: the registry — not Docker
container state — is the authoritative record of their existence and intent
(domain, repo, branch, auto_update, health flags). A production whose
container was removed must still be listed (as broken) instead of silently
vanishing. Runtime facts (container status, deployed commit) stay derived
from Docker/git at read time.

The file lives at ``{team.data_dir}/productions.json``. Like ports.json it
is team-shared state mutated from many threads and potentially from more
than one oduflow process, so every read-modify-write cycle runs under a
per-path mutex (threads) plus an flock on a sidecar file (processes) —
same pattern as :mod:`oduflow.port_registry`.

Top-level schema::

    {
      "version": 1,
      "webhook_secret": "<auto-generated with the first production>",
      "productions": {
        "<name>": {
          "name": ..., "domain": ..., "repo_url": ..., "branch": ...,
          "odoo_image": ..., "git_user": ..., "extra_addons": {...},
          "auto_update": false, "created_at": "...",
          "unhealthy": false, "deploy_in_progress": false,
          "meta": {},        # free-form attach point (reserved)
          "backup": {}       # backup subsystem state (schedule, last run)
        }
      }
    }
"""

from __future__ import annotations

import fcntl
import json
import logging
import os
import secrets
import tempfile
import threading
from contextlib import contextmanager
from typing import Any, Iterator

from oduflow.errors import ConflictError, NotFoundError
from oduflow.settings import TeamSettings

logger = logging.getLogger("oduflow")

_REGISTRY_FILENAME = "productions.json"

_locks_guard = threading.Lock()
_path_locks: dict[str, threading.Lock] = {}


def registry_path(team: TeamSettings) -> str:
    return os.path.join(team.data_dir, _REGISTRY_FILENAME)


def _thread_lock(path: str) -> threading.Lock:
    with _locks_guard:
        lock = _path_locks.get(path)
        if lock is None:
            lock = threading.Lock()
            _path_locks[path] = lock
        return lock


@contextmanager
def _registry_lock(path: str) -> Iterator[None]:
    """Serialize registry read-modify-write across threads and processes."""
    with _thread_lock(path):
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        fd = os.open(path + ".lock", os.O_RDWR | os.O_CREAT, 0o644)
        try:
            fcntl.flock(fd, fcntl.LOCK_EX)
            yield
        finally:
            fcntl.flock(fd, fcntl.LOCK_UN)
            os.close(fd)


def _empty_state() -> dict[str, Any]:
    return {"version": 1, "webhook_secret": "", "productions": {}}


def _load_state(path: str) -> dict[str, Any]:
    if not os.path.isfile(path):
        return _empty_state()
    try:
        with open(path) as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        # Never silently reset a productions registry: unlike ports.json this
        # is the source of truth for precious resources.
        raise RuntimeError(f"Corrupt productions registry {path}: {e}") from e
    if not isinstance(data, dict) or not isinstance(data.get("productions"), dict):
        raise RuntimeError(f"Malformed productions registry {path}")
    data.setdefault("version", 1)
    data.setdefault("webhook_secret", "")
    return data


def _save_state(path: str, state: dict[str, Any]) -> None:
    """Atomically save the registry. Callers must hold ``_registry_lock``."""
    dir_name = os.path.dirname(path) or "."
    fd, tmp_path = tempfile.mkstemp(prefix="productions.", suffix=".tmp", dir=dir_name)
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(state, f, indent=2, sort_keys=True)
            f.flush()
            os.fsync(f.fileno())
        # The registry holds the team webhook secret — keep it private.
        os.chmod(tmp_path, 0o600)
        os.replace(tmp_path, path)
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def load_state(team: TeamSettings) -> dict[str, Any]:
    """Read-only snapshot of the whole registry state."""
    return _load_state(registry_path(team))


def list_productions(team: TeamSettings) -> dict[str, dict[str, Any]]:
    prods: dict[str, dict[str, Any]] = load_state(team)["productions"]
    return prods


def get_production(team: TeamSettings, name: str) -> dict[str, Any]:
    prods = list_productions(team)
    if name not in prods:
        raise NotFoundError(f"Production '{name}' not found (team '{team.team_id}').")
    return prods[name]


def create_production(
    team: TeamSettings, name: str, record: dict[str, Any]
) -> dict[str, Any]:
    """Insert a new production record; generates the team webhook secret on
    first use. Raises ConflictError if the name is taken."""
    path = registry_path(team)
    with _registry_lock(path):
        state = _load_state(path)
        if name in state["productions"]:
            raise ConflictError(
                f"Production '{name}' already exists (team '{team.team_id}')."
            )
        if not state["webhook_secret"]:
            state["webhook_secret"] = secrets.token_urlsafe(32)
        full = {
            "name": name,
            "domain": "",
            "repo_url": "",
            "branch": "",
            "odoo_image": "",
            "git_user": "",
            "extra_addons": {},
            "auto_update": False,
            "created_at": "",
            "unhealthy": False,
            "deploy_in_progress": False,
            "meta": {},
            "backup": {},
        }
        full.update(record)
        full["name"] = name
        state["productions"][name] = full
        _save_state(path, state)
        logger.info("Registered production '%s' (team %s)", name, team.team_id)
        return full


def update_production(
    team: TeamSettings, name: str, updates: dict[str, Any]
) -> dict[str, Any]:
    """Merge ``updates`` into an existing record and return the new record."""
    path = registry_path(team)
    with _registry_lock(path):
        state = _load_state(path)
        if name not in state["productions"]:
            raise NotFoundError(
                f"Production '{name}' not found (team '{team.team_id}')."
            )
        state["productions"][name].update(updates)
        _save_state(path, state)
        record: dict[str, Any] = state["productions"][name]
        return record


def set_nested(
    team: TeamSettings, name: str, section: str, updates: dict[str, Any]
) -> dict[str, Any]:
    """Merge ``updates`` into a nested dict section ("meta" or "backup").

    The attach point for the backup subsystem: it records schedules and
    last-run state here without the registry knowing its schema.
    """
    path = registry_path(team)
    with _registry_lock(path):
        state = _load_state(path)
        if name not in state["productions"]:
            raise NotFoundError(
                f"Production '{name}' not found (team '{team.team_id}')."
            )
        record: dict[str, Any] = state["productions"][name]
        nested = record.setdefault(section, {})
        if not isinstance(nested, dict):
            nested = {}
            record[section] = nested
        nested.update(updates)
        _save_state(path, state)
        return record


def delete_production(team: TeamSettings, name: str) -> None:
    path = registry_path(team)
    with _registry_lock(path):
        state = _load_state(path)
        if name in state["productions"]:
            del state["productions"][name]
            _save_state(path, state)
            logger.info("Deleted production '%s' (team %s)", name, team.team_id)


def get_webhook_secret(team: TeamSettings) -> str:
    """The team's GitHub webhook secret ("" until the first production)."""
    return str(load_state(team)["webhook_secret"])


def clear_stale_deploy_flags(team: TeamSettings) -> list[str]:
    """Reset deploy_in_progress left behind by a server that died mid-deploy.

    Called once at startup; returns the names that were cleared.
    """
    path = registry_path(team)
    if not os.path.isfile(path):
        return []
    cleared: list[str] = []
    with _registry_lock(path):
        state = _load_state(path)
        for name, record in state["productions"].items():
            if record.get("deploy_in_progress"):
                record["deploy_in_progress"] = False
                cleared.append(name)
        if cleared:
            _save_state(path, state)
            logger.warning(
                "Cleared stale deploy_in_progress for production(s): %s",
                ", ".join(cleared),
            )
    return cleared
